name: shelf_logger_example
description: A server app using the shelf package with RequestLogger.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  args: ^2.0.0
  request_logger:
    path: ../..
  shelf: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
